### ISSUE TITLE
Error when loading a chart, on every instrument

### ISSUE THREAD

**Issue by ibuildit** [BitMEX/ninjatrader-bitmex#9] opened 2018-01-21 19:54 UTC
![image](https://user-images.githubusercontent.com/5072873/35198312-35ea9a38-feed-11e7-8852-a355921237db.png)

I get this regardless of instrument. The data is loading, but it does not stream live.

**Comment by ryanfox** [comment] 2018-01-22 16:06
A little more information is needed to diagnose this. What version of NinjaTrader are you running? What version of the BitMEX plugin? Charts both load and stream live for me.

**Comment by ibuildit** [comment] 2018-01-22 21:13
I'm running Ninjatrader 8, latest and the latest build of BitMEX. I am getting the chart and feed now properly. But I still get the error.

**Comment by ibuildit** [comment] 2018-01-22 21:18
Actually it's still buggy for me. I'm getting a new error now. Also some charts do not load completely. This is the 60 min. On first load after NT start, it does not refresh the chart, I must manually refresh the data.
<img width="322" alt="screenshot_1" src="https://user-images.githubusercontent.com/5072873/35244893-0c9ff580-ffc2-11e7-83bf-0b020b717844.png">
<img width="313" alt="screenshot_2" src="https://user-images.githubusercontent.com/5072873/35244895-0cbb38d6-ffc2-11e7-9865-f7ae0172d1d8.png">
<img width="491" alt="screenshot_3" src="https://user-images.githubusercontent.com/5072873/35244896-0cd52a3e-ffc2-11e7-8f1c-fbf972423f80.png">

Fresh windows 10 install, actually a new machine this time. Fresh NT8 too. 100mbit connection, intel i7 powerhouse dell

**Comment by ibuildit** [comment] 2018-01-22 21:19
30 minute...  the lower tf's were ok
![image](https://user-images.githubusercontent.com/5072873/35244968-4604a406-ffc2-11e7-9966-9418d438b04c.png)

**Comment by ryanfox** [comment] 2018-01-23 16:48
What are the steps you go through to trigger the error, from when you start up NinjaTrader to the time you get the error messages?

**Comment by Pietvw** [comment] 2018-02-23 19:56
Mine does the same, all I have to do to get the error is either connect to the data feed or reload all historical data for any chart.

**Comment by ryanfox** [comment] 2018-02-27 18:02
This was caused by an issue with fetching two sets of data at once. This is fixed in [v1.0.6.](https://github.com/BitMEX/ninjatrader-bitmex/releases/tag/v1.0.6)

**Closed by ryanfox** 2018-02-27 18:02 UTC
